version: 0.0
os: linux

hooks:
  AfterInstall:
    - location: scripts/start_container
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_container
      timeout: 300
      runas: root

