#!/bin/bash

# Start the container

# Pull the Docker image from Docker Hub
docker pull sivahariu/aws_cicd_pipline_codedeploy

# Run the Docker image as a container
docker run -d -p 80:9090 sivahariu/aws_cicd_pipline_codedeploy
